import { apiFetch } from './localBackend';
import { AiCharacter, ChatMessage, UserProfile } from '../types';

/**
 * Check if a memory string is a meaningless pseudo-memory or mechanical fragment
 * (e.g., "对话提及: ...", "用户说了: ...", "第1句: ...", truncated strings)
 */
export function isPseudoMemory(mem: string): boolean {
  if (!mem || typeof mem !== 'string') return true;
  const trimmed = mem.trim();
  if (trimmed.length < 3) return true;

  // Mechanical prefixes generated by previous bug or auto slicing
  if (/^(对话提及|用户说了|第\d+句|聊天提及|对话记录|系统捕获)[:：]/i.test(trimmed)) {
    return true;
  }
  if (/^"?\s*(对话提及|用户说了|第\d+句|聊天提及)/i.test(trimmed)) {
    return true;
  }

  // Check for truncated snippet pattern like: 对话提及: "xxx..." or "xxx..."
  if (/^对话提及\s*[:：]?\s*".*?\.\.\."$/i.test(trimmed) || /^对话提及\s*[:：]?\s*".*?…"$/.test(trimmed)) {
    return true;
  }

  // Check if it's purely a quote ending with ellipsis and under 30 chars without clear subject
  if (/^"[^"]{1,30}(\.\.\.|…)"$/.test(trimmed)) {
    return true;
  }

  return false;
}

/**
 * Filter character memories into valid memories and detected pseudo-memories for user preview and cleanup.
 */
export function cleanPseudoMemories(memories: string[] = []): {
  validMemories: string[];
  removedPseudoMemories: string[];
} {
  const validMemories: string[] = [];
  const removedPseudoMemories: string[] = [];

  for (const mem of memories) {
    if (isPseudoMemory(mem)) {
      removedPseudoMemories.push(mem);
    } else {
      validMemories.push(mem);
    }
  }

  return { validMemories, removedPseudoMemories };
}

/**
 * Check if candidate memory is semantically duplicate or covered by existing memories.
 */
export function isDuplicateMemory(existingMemories: string[] = [], candidate: string): boolean {
  if (!candidate || isPseudoMemory(candidate)) return true;

  const candClean = candidate.replace(/[^\w\u4e00-\u9fa5]/g, '').toLowerCase();
  if (!candClean) return true;

  for (const existing of existingMemories) {
    if (isPseudoMemory(existing)) continue;
    const existClean = existing.replace(/[^\w\u4e00-\u9fa5]/g, '').toLowerCase();
    if (!existClean) continue;

    // Exact normalized match
    if (existClean === candClean) return true;

    // Substring containment for sufficiently long strings (6+ chars)
    if (existClean.length >= 6 && candClean.length >= 6) {
      if (existClean.includes(candClean) || candClean.includes(existClean)) {
        return true;
      }
    }
  }

  return false;
}

export interface SmartMemoryExtractParams {
  character: AiCharacter;
  combinedUserText: string;
  recentMessages: ChatMessage[];
  userProfile?: UserProfile;
  apiConfig?: any;
  onUpdateCharacterMemories: (updatedMemories: string[]) => void;
}

// Rate limit / memory extraction lock per character
const lastExtractTimestampMap = new Map<string, number>();

/**
 * Triggers AI smart long-term memory extraction asynchronously.
 * Only extracts when genuine high-value personal facts, preferences, agreements, or goals are detected.
 */
export async function triggerSmartMemoryExtraction(params: SmartMemoryExtractParams): Promise<void> {
  const { character, combinedUserText, recentMessages, userProfile, apiConfig, onUpdateCharacterMemories } = params;

  if (!character || !combinedUserText) return;
  const trimmedInput = combinedUserText.trim();
  if (trimmedInput.length < 3) return;

  // Rate limit: extract at most once every 15 seconds per character
  const now = Date.now();
  const lastTime = lastExtractTimestampMap.get(character.id) || 0;
  if (now - lastTime < 15000) {
    return;
  }
  lastExtractTimestampMap.set(character.id, now);

  try {
    const res = await apiFetch('/api/gemini/extract-memories', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        character: {
          id: character.id,
          name: character.name,
          persona: character.persona,
        },
        userMessage: combinedUserText,
        recentMessages: recentMessages.map((m) => ({
          sender: m.sender,
          text: m.text,
        })),
        existingMemories: character.memories || [],
        userProfile: { name: userProfile?.name },
        apiConfig,
      }),
    });

    if (!res.ok) return;

    const data = await res.json();
    if (data.success && Array.isArray(data.extractedMemories) && data.extractedMemories.length > 0) {
      const currentMemories = [...(character.memories || [])];
      let hasNewMemory = false;

      for (const rawMem of data.extractedMemories) {
        if (typeof rawMem !== 'string') continue;
        const cleanMem = rawMem.trim();
        if (!cleanMem) continue;

        if (!isPseudoMemory(cleanMem) && !isDuplicateMemory(currentMemories, cleanMem)) {
          currentMemories.push(cleanMem);
          hasNewMemory = true;
        }
      }

      if (hasNewMemory) {
        console.log(`[SmartMemoryExtractor] New memory extracted for ${character.name}:`, currentMemories);
        onUpdateCharacterMemories(currentMemories);
      }
    }
  } catch (err) {
    console.warn('[SmartMemoryExtractor] Smart memory extraction failed:', err);
  }
}
